#!/usr/bin/env bash
# A script that will install Nginx web server
# and do some configurations

sudo apt-get -y update
sudo apt-get -y install nginx

# write 'Hello World!' in the root html file
#sudo echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo bash -c "echo 'Hello World!' > /var/www/html/index.html"

# check error syntax
sudo nginx -t

# start the Nginx web server
sudo service nginx start
