#!/usr/bin/env bash
# A script that will install Nginx web server
# and do some configurations

sudo apt-get -y update
sudo apt-get -y install nginx

# Change owner for nginx root directory
sudo chown -R $USER:$USER /var/www/

# write 'Hello World!' in the root html file
sudo echo 'Hello World!' > /var/www/html/index.html

# check error syntax
sudo nginx -t

# restart the Nginx web server
sudo service nginx restart
