#!/usr/bin/env bash
# A Bash script configure Nginx so that its HTTP response contains a custom header.

apt-get update -y
apt-get install nginx -y
echo "Hello World!" > /var/www/html/index.html
echo "Ceci n'est pas une page" > /var/www/html/404.html
sed -i "s/server_name _;/server_name _;\n\trewrite ^\/redirect_me https:\/\/facebook.com permanent;\n\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\t\tinternal;\n\t}/" /etc/nginx/sites-available/default
sed -i "s/include \/etc\/nginx\/sites-enabled\/\*;/include \/etc\/nginx\/sites-enabled\/\*;\n\tadd_header X-Served-By \"$HOSTNAME\";/" /etc/nginx/nginx.conf
service nginx start
