#!/usr/bin/env bash
# install and configure HAproxy load balancer

apt-get update -y
apt-get install --no-install-recommends software-properties-common -y
add-apt-repository ppa:vbernat/haproxy-2.8
apt-get install haproxy=2.8\* -y

echo "ENABLED=1" >> /etc/default/haproxy

echo "
	listen load_balancer
	bind *:80
	mode http
	balance roundrobin
	option httpclose
	option forwardfor
	server 437043-web-01 54.160.72.119:80 check
	server 437043-web-02 54.90.17.67:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start
