#!/usr/bin/env bash
# Nginx installation from listening on port 80.

rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-availabe/default /etc/nginx/sites-enables/default
sudo service nginx restart
