#!/bin/bash
total 20 -rwxr--r-- 1 root root  16 Jun  7 11:07 0-current_working_directory -rwxr--r-- 1 root root  59 Jun  7 11:42 1-listit -rwxr--r-- 1 root root  21 Jun  7 11:46 2-bring_me_home -rwxr--r-- 1 root root 231 Jun  7 11:49 3-listfiles -rw-r--r-- 1 root root  36 Jun  7 11:07 README.md
