#!/usr/bin/env bash
# Bash script that displays To infinity and beyond indefinitely.
# Dsipalys "I am invincible!!!" when receiving SIGTERM signal.

do
	echo "To infinity and beyond"
	sleep 2
	trap 'echo "I am invincible!!!"' SIGTERM
done
