#!/usr/bin/env bash
#Display "Best School" 10 times using while loop.

i=0
while [ "$i" -le 9 ]
do
	if [ "$i" -eq 8 ]
	then
		echo "Best School"
		echo "Hi"
	else
        	echo "Best School"
	fi
        i=$(( i + 1 ))
done
